### ISSUE TITLE
앱 주요 UI 와이어프레임 그리기

### ISSUE THREAD

**Issue by parksehee** [ProjectInTheClass/jae-jae#14]
### 주요 기능 정의
1. 상장 기업 검색
2. 검색된 상장 기업 재무상태표 보여주기
3. 재무상태표 내 각 요소별 비중 보여주기 (부채 00%, 자본 00% 등)
4. 봤던 기업의 재무상태표 따로 모아주기
5. 재무상태표 sns로 공유하기 (?)

**Comment by parksehee** [comment]
https://ovenapp.io/view/BmZCwWjvAjF49eXOKfyFUVIR5vVIdm1I/nr18o

**Comment by parksehee** [comment]
https://ovenapp.io/view/BmZCwWjvAjF49eXOKfyFUVIR5vVIdm1I/nr18o

**Comment by 37walks** [comment]
6f25a45
한 달 전 쯤에 공유드린 Storyboard 로 만든 프로토타입입니다. 참고 바랍니다.

**Comment by lovedlim** [comment]
완료!
